#define EBATTLE(type1,type2)\
class type1: type2 {\
    class ItemInfo: UniformItem {\
        mass = 40;\
    };\
}

EBATTLE(BRM_EBattleUNI_Green,BRM_BattleUNI_Base);
EBATTLE(BRM_EBattleUNI_Black,BRM_EBattleUNI_Green);
EBATTLE(BRM_EBattleUNI_BLUM,BRM_EBattleUNI_Green);
EBATTLE(BRM_EBattleUNI_Brown,BRM_EBattleUNI_Green);
EBATTLE(BRM_EBattleUNI_EMR,BRM_EBattleUNI_Green);
EBATTLE(BRM_EBattleUNI_NavyB,BRM_EBattleUNI_Green);
EBATTLE(BRM_EBattleUNI_CZRAIN,BRM_EBattleUNI_Green);
EBATTLE(BRM_EBattleUNI_SyrDIGI,BRM_EBattleUNI_Green);
EBATTLE(BRM_EBattleUNI_EGRAIN,BRM_EBattleUNI_Green);
EBATTLE(BRM_EBattleUNI_T07PLAT,BRM_EBattleUNI_Green);
EBATTLE(BRM_EBattleUNI_T07NAVY,BRM_EBattleUNI_Green);
EBATTLE(BRM_EBattleUNI_T07UNI,BRM_EBattleUNI_Green);
EBATTLE(BRM_EBattleUNI_T07ARTY,BRM_EBattleUNI_Green);

EBATTLE(BRM_EBattleUNIRS_Green,BRM_EBattleUNI_Green);
EBATTLE(BRM_EBattleUNIRS_Black,BRM_EBattleUNIRS_Green);
EBATTLE(BRM_EBattleUNIRS_BLUM,BRM_EBattleUNI_Green);
EBATTLE(BRM_EBattleUNIRS_Brown,BRM_EBattleUNIRS_Green);
EBATTLE(BRM_EBattleUNIRS_EMR,BRM_EBattleUNI_Green);
EBATTLE(BRM_EBattleUNIRS_NavyB,BRM_EBattleUNIRS_Green);
EBATTLE(BRM_EBattleUNIRS_CZRAIN,BRM_EBattleUNI_Green);
EBATTLE(BRM_EBattleUNIRS_SyrDIGI,BRM_EBattleUNI_Green);
EBATTLE(BRM_EBattleUNIRS_EGRAIN,BRM_EBattleUNI_Green);
EBATTLE(BRM_EBattleUNIRS_T07PLAT,BRM_EBattleUNI_Green);
EBATTLE(BRM_EBattleUNIRS_T07NAVY,BRM_EBattleUNI_Green);
EBATTLE(BRM_EBattleUNIRS_T07UNI,BRM_EBattleUNI_Green);
EBATTLE(BRM_EBattleUNIRS_T07ARTY,BRM_EBattleUNI_Green);

EBATTLE(BRM_EBattleUNITS_Green,BRM_EBattleUNI_Green);
EBATTLE(BRM_EBattleUNITS_Black,BRM_EBattleUNITS_Green);
EBATTLE(BRM_EBattleUNITS_BLUM,BRM_EBattleUNI_Green);
EBATTLE(BRM_EBattleUNITS_Brown,BRM_EBattleUNITS_Green);
EBATTLE(BRM_EBattleUNITS_EMR,BRM_EBattleUNI_Green);
EBATTLE(BRM_EBattleUNITS_NavyB,BRM_EBattleUNITS_Green);
EBATTLE(BRM_EBattleUNITS_CZRAIN,BRM_EBattleUNI_Green);
EBATTLE(BRM_EBattleUNITS_SyrDIGI,BRM_EBattleUNI_Green);
EBATTLE(BRM_EBattleUNITS_EGRAIN,BRM_EBattleUNI_Green);
EBATTLE(BRM_EBattleUNITS_T07PLAT,BRM_EBattleUNI_Green);
EBATTLE(BRM_EBattleUNITS_T07NAVY,BRM_EBattleUNI_Green);
EBATTLE(BRM_EBattleUNITS_T07UNI,BRM_EBattleUNI_Green);
EBATTLE(BRM_EBattleUNITS_T07ARTY,BRM_EBattleUNI_Green);
